/**
 * @file   test.java
 * @author Jiang Penghai <jphome98@gmail.com>
 * @date   Thu Feb 21 23:04:14 2013
 * 
 * @brief  
 * 
n * 
 */
/**
 * @file   test.cpp
 * @author Jiang Penghai <jphome98@gmail.com>
 * @date   Thu Feb 21 23:03:59 2013
 * 
 * @brief  
 * 
 * 
 */
/**
 * @file   test.c
 * @author Jiang Penghai <jphome98@gmail.com>
 * @date   Thu Feb 21 23:02:34 2013
 * 
 * @brief  
 * 
 * 
 */


int a;                          /**<  */
int b;                          /**< /**
                                 * @file   test.cpp
                                 * @author Jiang Penghai <jphome98@gmail.com>
                                 * @date   Thu Feb 21 23:10:09 2013
                                 * 
                                 * @brief  
                                 * 
                                 * 
                                 */
 */
///                             /**<  */

/**
 * 
 * 
 */
/**
 * 
 * 
 */
